from .authViews import RegisterView, LoginView, LogoutView,ProfileView
from .courseViews import CourseListView, CourseDetailView,MyCoursesProgressView,CourseSearchSuggestView,CourseReviewView
from .cartViews import CartView, CartDeleteView
from .paymentViews import CheckoutView, WebhookBankView
from .quizViews import QuizDetailView, QuizSubmitView,PracticeHistoryView,FinalExamHistoryView,QuizReviewDetailView,QuizLeaderboardView,PracticeQuizListView
from .lessonViews import LessonDetailView, MarkLessonCompleteView
from .interactionView import LessonCommentView,PersonalNoteView,ForumTopicView,ReplyToTopicView,GetReplyTopicView