# Generated by Django 6.0.2 on 2026-05-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_user_admin_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
