# Generated by Django 6.0.2 on 2026-05-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
