# Generated by Django 6.0.2 on 2026-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_forumresponse_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
