# Generated by Copilot on 2026-06-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_forumresponse_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='education.quiz')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('passage_text', models.TextField(blank=True, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('group_type', models.CharField(choices=[('kanji', 'Kanji'), ('reading', 'Reading'), ('listening', 'Listening'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('other', 'Other')], default='other', max_length=50)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='education.section')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='education.question')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FIBAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptable_text', models.CharField(max_length=255)),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fib_answers', to='education.question')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã đăng'), ('hidden', 'Ẩn')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.questiongroup'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(max_digits=3, decimal_places=1, default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Trắc nghiệm'), ('FILL_IN_BLANK', 'Điền vào chỗ trống')], default='MULTIPLE_CHOICE', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt_a',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt_b',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt_c',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt_d',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='quizsubmissionanswer',
            name='selected_choice',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='quizsubmissionanswer',
            name='selected_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]