# Generated by Django 6.0.2 on 2026-06-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_forumtopic_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('passage_text', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order_index', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='focus_area',
            field=models.CharField(default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_jlpt_template',
            field=models.BooleanField(default=False, help_text='Đề được tạo theo khung JLPT chuẩn (các phần thi cố định theo cấp độ).'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score_percent',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_code',
            field=models.CharField(blank=True, help_text='Mã kỳ thi JLPT, VD: 201907', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='education.questiongroup'),
        ),
        migrations.CreateModel(
            name='QuizSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('vocabulary', 'Từ vựng'), ('grammar', 'Ngữ pháp'), ('grammar_reading', 'Ngữ pháp & Đọc hiểu'), ('reading', 'Đọc hiểu'), ('listening', 'Nghe hiểu'), ('general', 'Tổng hợp')], default='general', max_length=20)),
                ('title_ja', models.CharField(blank=True, max_length=255)),
                ('title_vi', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_question_count', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='education.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='education.quizsection'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.quizsection'),
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('section', 'order')},
        ),
    ]
