# Generated by Copilot on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_exam_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='category',
            field=models.CharField(choices=[('grammar', 'Ngữ pháp & Từ vựng'), ('jlpt', 'JLPT & Luyện thi'), ('share', 'Chia sẻ kinh nghiệm'), ('find', 'Tìm bạn luyện tập'), ('qa', 'Hỏi đáp khóa học'), ('material', 'Tài liệu & Sách'), ('other', 'Khác')], default='other', max_length=20),
        ),
    ]