# Generated by Django 6.0.2 on 2026-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_forumtopic_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
