# Generated by Django 6.0.2 on 2026-06-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_jlpt_quiz_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='quizsection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizsection',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='focus_area',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_jlpt_template',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='passing_score_percent',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='session_code',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
        migrations.DeleteModel(
            name='QuizSection',
        ),
    ]
