# Generated by Django 6.0.2 on 2026-06-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_remove_question_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('duration', models.PositiveIntegerField(help_text='Thời lượng làm bài (phút)')),
                ('total_score', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Công bố'), ('hidden', 'Ẩn')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField(default=1)),
                ('content', models.TextField(help_text='Nội dung câu hỏi')),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Trắc nghiệm'), ('FILL_IN_BLANK', 'Điền từ')], max_length=20)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('explain_text', models.TextField(blank=True, help_text='Giải thích đáp án sau khi nộp bài')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='education.exam')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='FibAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptable_text', models.CharField(help_text='Chuỗi đáp án được chấp nhận', max_length=255)),
                ('is_case_sensitive', models.BooleanField(default=False, help_text='Có phân biệt hoa/thường không? Mặc định: không phân biệt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fib_answers', to='education.examquestion')),
            ],
            options={
                'db_table': 'fib_answers',
            },
        ),
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='education.examquestion')),
            ],
            options={
                'db_table': 'mcq_options',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, help_text='Hướng dẫn cho nhóm câu hỏi')),
                ('passage_text', models.TextField(blank=True, help_text='Đoạn văn đọc hiểu')),
                ('audio_url', models.URLField(blank=True, help_text='URL file audio nghe', null=True)),
                ('group_type', models.CharField(choices=[('text', 'Đoạn văn bản'), ('audio', 'File nghe'), ('none', 'Không có ngữ liệu')], default='none', max_length=10)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='education.examsection')),
            ],
            options={
                'db_table': 'question_groups',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.questiongroup'),
        ),
    ]
