# Generated by Django 6.0.2 on 2026-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_forumtopic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='exercise_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/exercises/'),
        ),
        migrations.AddField(
            model_name='material',
            name='exercise_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='vocab_examples',
            field=models.TextField(blank=True),
        ),
    ]
