# Generated by Django 6.0.2 on 2026-06-13 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_jlpt_exam_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve_user', 'Duyệt tài khoản'), ('reject_user', 'Từ chối tài khoản'), ('create_course', 'Thêm khóa học'), ('update_course', 'Sửa khóa học'), ('delete_course', 'Xóa khóa học'), ('create_chapter', 'Thêm chương'), ('update_chapter', 'Sửa chương'), ('delete_chapter', 'Xóa chương'), ('create_exam', 'Thêm đề thi'), ('update_exam', 'Sửa đề thi'), ('delete_exam', 'Xóa đề thi'), ('approve_topic', 'Duyệt bài thảo luận'), ('reject_topic', 'Từ chối bài thảo luận')], max_length=30)),
                ('target_description', models.CharField(blank=True, help_text='Tên đối tượng bị tác động', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại')], default='success', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
