# Generated by Django 6.0.2 on 2026-06-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_exam_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveConstraint(
            model_name='quiz',
            name='quiz_exactly_one_fk',
        ),
        migrations.RemoveIndex(
            model_name='quizsubmission',
            name='idx_submission_user_quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmissionanswer',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='quizsubmissionanswer',
            name='idx_submission_answer',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizsubmissionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizsubmissionanswer',
            name='submission',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuizSubmission',
        ),
        migrations.DeleteModel(
            name='QuizSubmissionAnswer',
        ),
    ]
