# Generated by Django 6.0.2 on 2026-06-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_remove_quiz_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
